version: 2

sources:
  - name: location_data
    description: "Raw data from the ETL"
    database: afyatekdb
    schema: public
    tables:
      - name: openmrs_location_mapping_final
        description: "Location data for CHWs."
